import os
import tempfile
import uuid
import streamlit as st
from shopping_agent import agent

st.set_page_config(page_title="AI Shopping Assistant", page_icon="🛒", layout="wide")

st.title("🛒 AI Shopping Assistant")
st.caption("Tell me what you want — I'll search, rate, and order the best match for you.")

# 1. Maintain a unique thread ID per browser tab/session
if "session_id" not in st.session_state:
    st.session_state.session_id = str(uuid.uuid4())

if "messages" not in st.session_state:
    st.session_state.messages = []

# LangGraph config tying memory to this specific session
config = {"configurable": {"thread_id": st.session_state.session_id}}

# Sidebar — shop by image
with st.sidebar:
    st.header("Shop by Image")
    st.caption("Upload a photo of a product and I'll find similar items in our store.")

    uploaded_file = st.file_uploader(
        "Upload product image", type=["jpg", "jpeg", "png", "webp"]
    )

    if uploaded_file:
        st.image(uploaded_file, use_container_width=True)

    if uploaded_file and st.button("Find similar products", use_container_width=True):
        suffix = os.path.splitext(uploaded_file.name)[1] or ".jpg"
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
            tmp.write(uploaded_file.getvalue())
            image_path = tmp.name

        prompt = f"I uploaded a product image. Please analyze it and find similar products in the store. Image path: {image_path}"
        st.session_state.messages.append({"role": "user", "content": prompt})
        st.session_state.pending_image = uploaded_file.name
        st.rerun()

# Render chat history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        if msg["role"] == "user" and msg["content"].startswith("I uploaded a product image"):
            filename = msg["content"].split("Image path:")[-1].strip()
            st.markdown(f"Searching by image: **{os.path.basename(filename)}**")
        else:
            st.markdown(msg["content"].replace("$", r"\$"))

# Handle pending image search trigger
if (
    st.session_state.messages
    and st.session_state.messages[-1]["role"] == "user"
    and "pending_image" in st.session_state
):
    last_user_prompt = st.session_state.messages[-1]["content"]
    with st.chat_message("assistant"):
        with st.spinner("Analyzing image and searching…"):
            # Pass only the new message + checkpointer config
            result = agent.invoke(
                {"messages": [{"role": "user", "content": last_user_prompt}]},
                config=config,
            )
            response = result["messages"][-1].content.replace("`", "")
        st.markdown(response.replace("$", r"\$"))

    st.session_state.messages.append({"role": "assistant", "content": response})
    del st.session_state.pending_image
    st.rerun()

# Text chat input
if prompt := st.chat_input("e.g. I want organic honey under $15 with 4+ rating"):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        # Live status box showing tool calls to the class
        with st.status("Agent Reasoning & Tool Execution...", expanded=True) as status:
            response_text = ""
            for step in agent.stream(
                {"messages": [{"role": "user", "content": prompt}]},
                config=config,
                stream_mode="values"
            ):
                latest_msg = step["messages"][-1]
                
                # Show tool calls when generated by LLM
                if hasattr(latest_msg, "tool_calls") and latest_msg.tool_calls:
                    for tc in latest_msg.tool_calls:
                        st.write(f"🔧 **Invoking Tool:** `{tc['name']}` with args `{tc['args']}`")
                
                # Show tool observations returned from functions
                elif latest_msg.type == "tool":
                    st.write(f"📥 **Observation from {latest_msg.name}:** `{latest_msg.content[:120]}...`")
                
                # Capture final agent response
                elif latest_msg.type == "ai" and not latest_msg.tool_calls:
                    response_text = latest_msg.content

            status.update(label="Response Generated!", state="complete", expanded=False)

        st.markdown(response_text.replace("$", r"\$"))

    st.session_state.messages.append({"role": "assistant", "content": response_text})
    st.rerun()